--- LIBRARIES
-- __AETHR.Include( AETHR_LIBRARIES_FOLDER ..'/json/json.lua' )
__AETHR.Include( AETHR_LIBRARIES_FOLDER ..'/MOOSE/Moose.lua' )
__AETHR.Include( AETHR_LIBRARIES_FOLDER ..'/MIST/mist.lua' )

--- AETHER 
__AETHR.Include( AETHR_DEVELOPMENT_FOLDER ..'/AETHR.lua' )
__AETHR.Include( AETHR_DEVELOPMENT_FOLDER ..'/ENUMS.lua' )
__AETHR.Include( AETHR_DEVELOPMENT_FOLDER ..'/customTypes.lua' )
__AETHR.Include( AETHR_DEVELOPMENT_FOLDER ..'/CONFIG.lua' )
__AETHR.Include( AETHR_DEVELOPMENT_FOLDER ..'/POLY.lua' )
__AETHR.Include( AETHR_DEVELOPMENT_FOLDER ..'/IO.lua' )
__AETHR.Include( AETHR_DEVELOPMENT_FOLDER ..'/FILEOPS.lua' )
__AETHR.Include( AETHR_DEVELOPMENT_FOLDER ..'/WORLD.lua' )
__AETHR.Include( AETHR_DEVELOPMENT_FOLDER ..'/MATH.lua' )
__AETHR.Include( AETHR_DEVELOPMENT_FOLDER ..'/ZONE_MANAGER.lua' )
__AETHR.Include( AETHR_DEVELOPMENT_FOLDER ..'/AUTOSAVE.lua' )


--- MIZ SCRIPTS
__AETHR.Include( AETHR_MIZ_FOLDER ..'/scripts/1_Setup.lua' )
__AETHR.Include( AETHR_MIZ_FOLDER ..'/scripts/2_FirstRun.lua' )
__AETHR.Include( AETHR_MIZ_FOLDER ..'/scripts/3_Main.lua' )

