--- @class AETHR.ENUMS
--- @brief ENUMS for AETHR
---@diagnostic disable: undefined-global
AETHR.ENUMS = {
    ObjectCategory = {
        UNIT = Object.Category.UNIT,
        WEAPON = Object.Category.WEAPON,
        STATIC = Object.Category.STATIC,
        SCENERY = Object.Category.SCENERY,
        BASE = Object.Category.BASE
    },
    UnitCategory = {
        AIRPLANE = Unit.Category.AIRPLANE,
        HELICOPTER = Unit.Category.HELICOPTER,
        GROUND_UNIT = Unit.Category.GROUND_UNIT,
        SHIP = Unit.Category.SHIP,
        STRUCTURE = Unit.Category.STRUCTURE
    },
    GroupCategory = {
        AIRPLANE = Group.Category.AIRPLANE,
        HELICOPTER = Group.Category.HELICOPTER,
        GROUND = Group.Category.GROUND,
        SHIP = Group.Category.SHIP
    },
    AirbaseCategory = {
        AIRDROME = Airbase.Category.AIRDROME,
        HELIPAD = Airbase.Category.HELIPAD,
        SHIP = Airbase.Category.SHIP
    },
    SurfaceType = {
        LAND = land.SurfaceType.LAND,
        SHALLOW_WATER = land.SurfaceType.SHALLOW_WATER,
        WATER = land.SurfaceType.WATER,
        ROAD = land.SurfaceType.ROAD,
        RUNWAY = land.SurfaceType.RUNWAY,
    },
    Events = {
        S_EVENT_SHOT = world.event.S_EVENT_SHOT,
        S_EVENT_HIT = world.event.S_EVENT_HIT,
        S_EVENT_TAKEOFF = world.event.S_EVENT_TAKEOFF,
        S_EVENT_LAND = world.event.S_EVENT_LAND,
        S_EVENT_CRASH = world.event.S_EVENT_CRASH,
        S_EVENT_EJECTION = world.event.S_EVENT_EJECTION,
        S_EVENT_REFUELING = world.event.S_EVENT_REFUELING,
        S_EVENT_DEAD = world.event.S_EVENT_DEAD,
        S_EVENT_PILOT_DEAD = world.event.S_EVENT_PILOT_DEAD,
        S_EVENT_BASE_CAPTURED = world.event.S_EVENT_BASE_CAPTURED,
        S_EVENT_MISSION_START = world.event.S_EVENT_MISSION_START, -- currently can not be caught in script due to happens before script load
        S_EVENT_MISSION_END = world.event.S_EVENT_MISSION_END,     -- currently can not be caught in script due to happens before script load
        S_EVENT_TOOK_CONTROL = world.event.S_EVENT_TOOK_CONTROL,
        S_EVENT_REFUELING_STOP = world.event.S_EVENT_REFUELING_STOP,
        S_EVENT_BIRTH = world.event.S_EVENT_BIRTH,
        S_EVENT_HUMAN_FAILURE = world.event.S_EVENT_HUMAN_FAILURE,
        S_EVENT_ENGINE_STARTUP = world.event.S_EVENT_ENGINE_STARTUP,
        S_EVENT_ENGINE_SHUTDOWN = world.event.S_EVENT_ENGINE_SHUTDOWN,
        S_EVENT_PLAYER_ENTER_UNIT = world.event.S_EVENT_PLAYER_ENTER_UNIT,
        S_EVENT_PLAYER_LEAVE_UNIT = world.event.S_EVENT_PLAYER_LEAVE_UNIT,
        S_EVENT_PLAYER_COMMENT = world.event.S_EVENT_PLAYER_COMMENT,
        S_EVENT_SHOOTING_START = world.event.S_EVENT_SHOOTING_START,
        S_EVENT_SHOOTING_END = world.event.S_EVENT_SHOOTING_END,
        S_EVENT_MARK_ADDED = world.event.S_EVENT_MARK_ADDED,
        S_EVENT_MARK_CHANGE = world.event.S_EVENT_MARK_CHANGE,
        S_EVENT_MARK_REMOVED = world.event.S_EVENT_MARK_REMOVED,
        S_EVENT_KILL = world.event.S_EVENT_KILL,
        S_EVENT_SCORE = world.event.S_EVENT_SCORE,
        S_EVENT_UNIT_LOST = world.event.S_EVENT_UNIT_LOST,
        S_EVENT_LANDING_AFTER_EJECTION = world.event.S_EVENT_LANDING_AFTER_EJECTION,
        S_EVENT_PARATROOPER_LENDING = world.event.S_EVENT_PARATROOPER_LENDING,
        S_EVENT_DISCARD_CHAIR_AFTER_EJECTION = world.event.S_EVENT_DISCARD_CHAIR_AFTER_EJECTION,
        S_EVENT_WEAPON_ADD = world.event.S_EVENT_WEAPON_ADD,
        S_EVENT_TRIGGER_ZONE = world.event.S_EVENT_TRIGGER_ZONE,
        S_EVENT_LANDING_QUALITY_MARK = world.event.S_EVENT_LANDING_QUALITY_MARK,
        S_EVENT_BDA = world.event.S_EVENT_BDA,
        S_EVENT_AI_ABORT_MISSION = world.event.S_EVENT_AI_ABORT_MISSION,
        S_EVENT_DAYNIGHT = world.event.S_EVENT_DAYNIGHT,
        S_EVENT_FLIGHT_TIME = world.event.S_EVENT_FLIGHT_TIME,
        S_EVENT_PLAYER_SELF_KILL_PILOT = world.event.S_EVENT_PLAYER_SELF_KILL_PILOT,
        S_EVENT_PLAYER_CAPTURE_AIRFIELD = world.event.S_EVENT_PLAYER_CAPTURE_AIRFIELD,
        S_EVENT_EMERGENCY_LANDING = world.event.S_EVENT_EMERGENCY_LANDING,  -- useful event to handle when a bot ditches, and "group dead" condition can't be met 
    },
    Coalition = {
        NEUTRAL = coalition.side.NEUTRAL,
        RED = coalition.side.RED,
        BLUE = coalition.side.BLUE,
    },
    Phonetic = {
        A = 'Alpha',
        B = 'Bravo',
        C = 'Charlie',
        D = 'Delta',
        E = 'Echo',
        F = 'Foxtrot',
        G = 'Golf',
        H = 'Hotel',
        I = 'India',
        J = 'Juliett',
        K = 'Kilo',
        L = 'Lima',
        M = 'Mike',
        N = 'November',
        O = 'Oscar',
        P = 'Papa',
        Q = 'Quebec',
        R = 'Romeo',
        S = 'Sierra',
        T = 'Tango',
        U = 'Uniform',
        V = 'Victor',
        W = 'Whiskey',
        X = 'Xray',
        Y = 'Yankee',
        Z = 'Zulu',
    },
}
